### ISSUE TITLE
TypeError: Cannot call method 'indexOf' of undefined

### ISSUE THREAD

**Issue by jpsilvashy** [chriswhong/uber-trip-script#11]
I'm not too savvy with node, after all my trips are downloaded, it starts processing them, at some point in the process I get:

```
TypeError: Cannot call method 'indexOf' of undefined
    at Object.<anonymous> (/Users/jpsilvashy/Projects/hack/uber-trip-script/app.js:212:15)
    at exports.each (/Users/jpsilvashy/Projects/hack/uber-trip-script/node_modules/cheerio/lib/api/traversing.js:268:24)
    at parseStats (/Users/jpsilvashy/Projects/hack/uber-trip-script/app.js:177:27)
    at Request._callback (/Users/jpsilvashy/Projects/hack/uber-trip-script/app.js:141:12)
    at Request.self.callback (/Users/jpsilvashy/Projects/hack/uber-trip-script/node_modules/request/request.js:344:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Users/jpsilvashy/Projects/hack/uber-trip-script/node_modules/request/request.js:1239:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/jpsilvashy/Projects/hack/uber-trip-script/node_modules/request/request.js:1187:12)
    at IncomingMessage.emit (events.js:117:20)
```

I have a lot of trips, 64 pages of them, maybe that is too many?

**Comment by chriswhong** [comment]
Yeah try to take it down to 9 and see if it works.

**Comment by chriswhong** [comment]
Maybe this fixes your error? https://github.com/chriswhong/uber-trip-script/pull/12/
